### ISSUE TITLE
what is the relationship between yumi_support/rapid and yumi_hw/rapid/ROS_control ? can I only use the former one instead of the latter one?

### ISSUE THREAD

**Issue by JJHu1993** [OrebroUniversity/yumi#10]
what is the relationship between    yumi_support/rapid    and     yumi_hw/rapid/ROS_control ?
Because I can understand the yumi_support/rapid files: each arm have a motion server and state server unlike the files in yumi_hw/rapid/ROS_control which didn't contain a motion_server.

So can I only use the former one: yumi_support/rapid?

**Comment by tstoyanov** [comment]
yumi_support/rapid contains modules for running trajectory downloading to the robot. This is the preferred way to interface if you are using move_it and trajectory action interfaces. 

The yumi_hw/rapid folder is used if you are setting up a ros_control hardware interface. In that case you are directly giving control setpoints, instead of downloading a trajectory. Commands are executed immediately, and feedback sent on the same connection object back to the ROS side. This is the preferd mode for running ros_control controllers. At the moment, this interface runs at about 10Hz. 

That said, the moveit interface has not been extensively tested, so there might still be bugs in there. I also need to check if I have uploaded the latest versions from our robot to the repository.
